language: java
sudo: required

jdk:
  #- oraclejdk8
  - openjdk12

# ToDo Temporary disabled to speed up testing
# install: ./stuff/install-dependencies-travisci-ubuntu1404.sh

after_success:
  - ./gradlew jacocoRootReport coveralls